### ISSUE TITLE
Attempt to snapshot an instance twice

### ISSUE THREAD

**Issue by peteroruba** [p-prakash/aws-lambda-functions#1]
I have a single EC2 instance with a set of tags, one of which is my backup tag, but there are other tags as well. By looking at the lambda log I see that there is an error reporting a snapshot has been requested twice, failing at the second attempt due to a too short time distance. Concluding from that I assume the list with instance to backup is populated with a duplicate entry of my single instance.

**Comment by p-prakash** [comment]
@peteroruba I'll check and get back to you on that. May be in a week.

**Comment by p-prakash** [comment]
@peteroruba Sorry for a long delay. If you are still looking for a solution please check the solution in AWS Answers - https://aws.amazon.com/answers/infrastructure-management/ebs-snapshot-scheduler/
